### ISSUE TITLE
Linux PowerPC: Endian issues

### ISSUE THREAD

**Issue by chzigotzky** [phoboslab/wipeout-rewrite#56]
Hello,

Thanks a lot for wipEout Rewrite! :-)

I was able to compile it on ubuntu MATE 16.04.7 PowerPC today. It starts but it has wrong colors and the sound isn't correct. I think it is an endian issue because Linux PowerPC runs on big endian machines.
I tested it on Void PPC as well but unfortunately it has the same issues on it.
Is it possible to fix these issues?

Screenshot:

![wipEout_Rewrite_Linux_PowerPC](https://github.com/phoboslab/wipeout-rewrite/assets/43322007/48cd5647-0075-4f36-8cbd-69bce55a5976)

Thanks,
Christian

**Comment by Jamesf4** [comment]
Littlebit but still Cool

ส่งจาก Outlook for iOS<https://aka.ms/o0ukef>
________________________________
จาก: Christian Zigotzky ***@***.***>
ส่ง: Monday, August 28, 2023 11:29:26 AM
ถึง: phoboslab/wipeout-rewrite ***@***.***>
สำเนาถึง: Subscribed ***@***.***>
ชื่อเรื่อง: [phoboslab/wipeout-rewrite] Linux PowerPC: Endian issues (Issue #56)


Hello,

Thanks a lot for wipEout Rewrite! :-)

I was able to compile it on ubuntu MATE 16.04.7 PowerPC today. It starts but it has wrong colors and the sound isn't correct. I think it is an endian issue because Linux PowerPC runs on big endian machines.
I tested it on Void PPC as well but unfortunately it has the same issues on it.
Is it possible to fix these issues?

Screenshot:

[wipEout_Rewrite_Linux_PowerPC]<https://user-images.githubusercontent.com/43322007/263642597-48cd5647-0075-4f36-8cbd-69bce55a5976.png>

Thanks,
Christian

**Comment by phoboslab** [comment]
Very cool to see that you got it running at all!

Questions:
- does the music work and only sound effects are garbled?
- do you see the title screen in the correct colors?

The title screen is in straight 16bit colors, while most (all?) of the textures are paletted. I assume reading the colors from the palette isn't endian agnostic. The palette lookup seems to work though.

I have a harder time to understand where the sound issues come from. The `wipeout.vb` file with all the samples is [read one byte at a time](https://github.com/phoboslab/wipeout-rewrite/blob/master/src/wipeout/sfx.c#L91-L94). If there's issues with the music, there is probably a bug in the [QOA decoder](https://github.com/phoboslab/qoa) itself. You can change the volume of sound effects and music in the main options to check what exactly is broken.

**Comment by chzigotzky** [comment]
Thanks for your fast answer. The color issue is partly fixed with your commit. :-)

![wipEout_1](https://github.com/phoboslab/wipeout-rewrite/assets/43322007/2d720676-b0ce-4238-9acd-61c58a01831e)

![wipEout_2](https://github.com/phoboslab/wipeout-rewrite/assets/43322007/f1f986ad-6e7d-44cf-991b-128c0242a0e6)

![wipEout_3](https://github.com/phoboslab/wipeout-rewrite/assets/43322007/4c9f0afa-ef05-48ac-a59e-c4fdc761e7df)

Musik and sound effects are both garbled.

**Comment by BeWorld2018** [comment]
Thanks for this fix, I had the same problem under MorphOS PPC.

For audio, you can modify this : https://github.com/phoboslab/wipeout-rewrite/blob/master/src/platform_sdl.c#L393
Put AUDIO_F32SYS

**Comment by chzigotzky** [comment]
Yes, the audio fix works! :-) Thanks!

There are still some color issues.

**Comment by phoboslab** [comment]
I suspect I was overly smart; trying to swap the palette in-place. Which doesn't work when the whole `get_u16_le()` function is inlined. Hope that was it :]

**Comment by chzigotzky** [comment]
Many thanks for your help! :-) The colors partly arent't correct but it looks really better.

![wipEout_4](https://github.com/phoboslab/wipeout-rewrite/assets/43322007/fd74d303-6e18-4e07-be40-ca1e30f6f064)

**Comment by BeWorld2018** [comment]
In my side, i use OpenGL Legacy renderer from unoffical repository : https://github.com/mrneo240/wipeout-rewrite/blob/master/src/render_gl_legacy.c
but i have some problem with colors, i think i's better now but not perfect :

with MorphOS (PPC): 
![image](https://github.com/phoboslab/wipeout-rewrite/assets/36823759/81e12687-64b9-4251-9679-effbf25b5355)

with Windows (same renderer):
![image](https://github.com/phoboslab/wipeout-rewrite/assets/36823759/158fdca1-8e3f-49a4-a54f-7da788943364)

**Comment by phoboslab** [comment]
Texture loading seems to work now, but the vertex colors for the track are backwards!? I'm looking into it.

Also, judging from the trees, this legacy OpenGL renderer is missing a `glEnable(GL_ALPHA_TEST)` :]

**Comment by BeWorld2018** [comment]
> Also, judging from the trees, this legacy OpenGL renderer is missing a `glEnable(GL_ALPHA_TEST)` :]

You right, i put that and tree are now correct, thanks

**Comment by phoboslab** [comment]
Well, I can't find anything wrong with the texture loading and I have no way to test big endian machines. Is there maybe some way I can do this in a VM?

Also, if you have a minute, can you please try and change [this line](https://github.com/phoboslab/wipeout-rewrite/blob/master/src/render_gl.c#L159) from 

```c
vec4 color = tex_color * v_color;
```

to 
```c
vec4 color = v_color;
```

This will disable texture rendering. If you then enter the game, we can at least check if a) the vertex colors are wrong or b) it's still the texture loading.

**Comment by phoboslab** [comment]
Thanks for the screenshot! So it was the vertex colors and initializing them with `rgba_t color = {.as_uint32 = get_i32_le(bytes, &p) | 0xff000000};` _obviously_ didn't work. Above commit should fix that.

I will clean up the code a little and get rid of the `.as_uint32` union completely. I believe that was the only instance it was used anyway.

**Comment by chzigotzky** [comment]
The colors are all correct! Thanks a lot! :-) I compiled it on an old ubuntu MATE 16.04.7 PowerPC and it works without any problems.
I also compiled and tested it on Void PPC and on a new Debian Sid PPC but unfortunately the sound stutters sometimes.

**Comment by chzigotzky** [comment]
The intro video also stutters on Void PPC and Debian PPC. An SDL issue?

They don't stutter on the old ubuntu MATE 16.04.7 PowerPC.

**Comment by phoboslab** [comment]
Sound stuttering can maybe be fixed by increasing the buffer size [here](https://github.com/phoboslab/wipeout-rewrite/blob/master/src/platform_sdl.c#L395) at the cost of some sound latency. Try setting it to `.samples = 4096,` or even higher. Let me know if that helps; I can add that as in-game option.

As for the video: how's the CPU load during the intro?

**Comment by chzigotzky** [comment]
Thank you very much for your answer! Unfortunately, setting it to .samples = 4096 does not solve the stuttering problem. Even a higher level does not solve the problem.

During the stuttering the CPU load is about 90%.

**Comment by chzigotzky** [comment]
When I start a race, the sound stutters and the CPU usage increases to 90%. A short time later, the stuttering goes away and the CPU usage decreases.

Maybe I should test it with the libsdl2 from ubuntu MATE 16.04.7. (LD_LIBRARY_PATH)

**Comment by phoboslab** [comment]
> Result MorphOS/Windows with OpenGL legacy 👍 (Track border seem yellow instead of purple)

Not really sure what's going on with the track colors, but the color blotches in the audience stands could be from an overflow!? I think this:
```
uint8_t R = tris.vertices[i].color.as_rgba.r;
uint8_t G = tris.vertices[i].color.as_rgba.g;
uint8_t B = tris.vertices[i].color.as_rgba.b;
if(R == 128){
	R = 255;
} else {
	R *=2;
}
if(G == 128){
	G = 255;
} else {
	G *=2;
}
if(B == 128){
	B = 255;
} else {
	B *=2;
}
tris.vertices[i].color.as_rgba.r = R;
tris.vertices[i].color.as_rgba.g = G;
tris.vertices[i].color.as_rgba.b = B;
```

should just be (sans `as_rgba` as removed in a commit today)

```
tris.vertices[i].color.r = clamp(tris.vertices[i].color.r * 2, 0, 255);
tris.vertices[i].color.g = clamp(tris.vertices[i].color.g * 2, 0, 255);
tris.vertices[i].color.b = clamp(tris.vertices[i].color.b * 2, 0, 255);
```

Or `glColorPointer()` needs to be float and you divide all color values by `128.0`. For whatever reason wipEout mostly seems to use the `0..128` color range, but then sometimes exceeds it with `> 128` "whiter than white" overbright values.

**Comment by BeWorld2018** [comment]
You right on first solution !
Thanks again ;-)
![image](https://github.com/phoboslab/wipeout-rewrite/assets/36823759/716d1efb-f02e-4810-9803-b6348833d551)

**Comment by chzigotzky** [comment]
I have found the issue. -> A L T I V E C

We have stuttering on Void PPC on a Non-AltiVec PowerPC machine. (FSL P50x0)

We don't have stuttering on Void PPC on a PowerPC machine with a SoC with AltiVec support. (P.A. Semi PA6T)

It seems the libs on ubuntu MATE 16.04.7 PowerPC aren't compiled with AltiVec support so wipEout runs without stuttering on a Non-AltiVec PowerPC machine.

Is it possible to compile a static wipEout binary (.a)? Maybe this is a solution.

**Comment by chzigotzky** [comment]
Hi BeWorld,

Congratulations! Maybe I should test the OpenGL Legacy renderer version as well.

Could you please share your modified source code of the OpenGL Legacy renderer version?

**Comment by chzigotzky** [comment]
Hi BeWorld,

Congratulations! Maybe I should test the OpenGL Legacy renderer version as well.

Could you please share your modified source code of the OpenGL Legacy renderer version?

Thanks,
Christian

**Comment by chzigotzky** [comment]
Hi All,

I patched the OpenGL Legacy renderer version and it runs without any stuttering on Void PPC on my Non-AltiVec PowerPC machine.

There are some graphical issues for example missing transparency.

![wipEout_legacy_render_Linux_PPC](https://github.com/phoboslab/wipeout-rewrite/assets/43322007/7ab9787a-7798-47ea-9bee-0e14adf9aece)

**Comment by BeWorld2018** [comment]
hi,
i just add after line 114
`glEnable(GL_ALPHA_TEST);`
And add patch:
```
void render_push_tris(tris_t tris, uint16_t texture_index) {
	error_if(texture_index >= textures_len, "Invalid texture %d", texture_index);

	if (tris_len >= RENDER_TRIS_BUFFER_CAPACITY) {
		render_flush();
	}
	if(texture_index != texture_index_prev){
		render_flush();
	}
	texture_index_prev = texture_index;

	render_texture_t *t = &textures[texture_index];

	for (int i = 0; i < 3; i++) {
		
		// resize back to (0,1) uv space
		tris.vertices[i].uv.x = (tris.vertices[i].uv.x / t->size.x) * t->scale.x;
		tris.vertices[i].uv.y = (tris.vertices[i].uv.y / t->size.y) * t->scale.y;
		if(tris.vertices[i].color.a == 0){
			continue;
		}
		tris.vertices[i].color.r = clamp(tris.vertices[i].color.r * 2, 0, 255);
		tris.vertices[i].color.g = clamp(tris.vertices[i].color.g * 2, 0, 255);;
		tris.vertices[i].color.b = clamp(tris.vertices[i].color.b * 2, 0, 255);;
		
	}
	tris_buffer[tris_len++] = tris;
}

```

And i add patch to release textures when exit game
`void render_cleanup(void) {
	// TODO
	render_textures_reset(render_textures_len());
	
}`

**Comment by BeWorld2018** [comment]
i recompare my file with original opengl legacy file and all difference are mentioned in my reply.

**Comment by chzigotzky** [comment]
BeWorld,

Thanks for your answer. It works with the correct colors and sound now! :-)

Many thanks to all! :-)

Cheers,
Christian

**Comment by chzigotzky** [comment]
It works with the correct colors and without sound stutters with my AMD Radeon HD6970 (Cayman XT).

Unfortunately it has color issues with the ATi Radeon X1900 XT (R580):

![Screenshot-at-2023-09-02-15-23-25](https://github.com/phoboslab/wipeout-rewrite/assets/43322007/ffce7af7-2308-4f1c-b983-27ecfe83da4e)

**Comment by madskateman** [comment]
> It works with the correct colors and without sound stutters with my AMD Radeon HD6970 (Cayman XT).
> 
> Unfortunately it has color issues with the ATi Radeon X1900 XT (R580):
> 
> ![Screenshot-at-2023-09-02-15-23-25](https://user-images.githubusercontent.com/43322007/265215853-ffce7af7-2308-4f1c-b983-27ecfe83da4e.png)

On this PPC machine the BeWorld MorphOS port is working perfect. So the X1900 (R580) GPU is ok.  

Link to MorphOS Screenshot  [https://www.skateman.nl/wp-content/uploads/2023/09/MOS_WIPEOUT.jpg](url)

**Comment by phoboslab** [comment]
Closing this issue. The problems that remain seem to be driver specific. Feel free to open another issue if you find more problems with the game itself.
